title: Image analysis in Python
author: The scikit-image contributors
logo: 'images/logo.png'
exclude_patterns: ['workshops/*', '*/not_yet_booked/*', '*/solutions/*']
execute:
    execute_notebooks : 'auto'
